micronaut:
  application:
    name: tircalculator

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/calculator'
    username: 'user'
    password: 'password'
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
